"""Add total_time_minutes to Response

Revision ID: 18ffd5d51b9d
Revises: e6c08e965ec9
Create Date: 2025-05-05 18:51:45.162076

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '18ffd5d51b9d'
down_revision = 'e6c08e965ec9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_time_survey_minutes', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('total_time_survey_minutes')

    # ### end Alembic commands ###
