"""Add startup investments and time spent fields to Response

Revision ID: 1a3467967745
Revises: 58643c2ccf6f
Create Date: 2025-04-28 16:17:30.504450

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a3467967745'
down_revision = '58643c2ccf6f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('startup_investments', sa.JSON(), nullable=True))
        batch_op.add_column(sa.Column('startup_investment_duration', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('startup_investment_duration')
        batch_op.drop_column('startup_investments')

    # ### end Alembic commands ###
