"""Initial migration

Revision ID: 2124e3696613
Revises: 
Create Date: 2025-04-10 13:29:37.926765

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2124e3696613'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.Column('date_given', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consent_id')
    )
    op.create_table('response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.String(length=100), nullable=False),
    sa.Column('participant_id', sa.String(length=100), nullable=False),
    sa.Column('unique_code', sa.String(length=50), nullable=True),
    sa.Column('story_type', sa.String(length=20), nullable=True),
    sa.Column('user_answer', sa.String(length=300), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('completed', sa.Boolean(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('date_created', sa.DateTime(), nullable=False),
    sa.Column('date_updated', sa.DateTime(), nullable=False),
    sa.Column('startup_code', sa.String(length=50), nullable=True),
    sa.Column('founder_name', sa.String(length=100), nullable=True),
    sa.Column('failure_prob', sa.Float(), nullable=True),
    sa.Column('success_prob', sa.Float(), nullable=True),
    sa.Column('expected_return', sa.Float(), nullable=True),
    sa.Column('voyagemind_investment', sa.Float(), nullable=True),
    sa.Column('voyagemind_dollar_return', sa.Float(), nullable=True),
    sa.Column('startup_factors', sa.String(length=300), nullable=True),
    sa.Column('founder_factors', sa.String(length=300), nullable=True),
    sa.Column('gender', sa.String(length=20), nullable=True),
    sa.Column('age', sa.Integer(), nullable=True),
    sa.Column('education_level', sa.String(length=50), nullable=True),
    sa.Column('mturk_id', sa.String(length=100), nullable=True),
    sa.Column('completion_code', sa.String(length=50), nullable=True),
    sa.ForeignKeyConstraint(['consent_id'], ['user_consent.consent_id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consent_id'),
    sa.UniqueConstraint('participant_id'),
    sa.UniqueConstraint('unique_code')
    )
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.create_index('idx_response_consent_id', ['consent_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_index('idx_response_consent_id')

    op.drop_table('response')
    op.drop_table('user_consent')
    # ### end Alembic commands ###
