"""Added intention guess

Revision ID: 3a569ffa2737
Revises: 6ae70b9a1061
Create Date: 2025-06-19 18:03:21.912974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a569ffa2737'
down_revision = '6ae70b9a1061'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guess_intention', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('guess_intention')

    # ### end Alembic commands ###
