"""Initial migration.

Revision ID: 7327765666a5
Revises: 
Create Date: 2025-02-24 19:59:32.710634

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7327765666a5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_consent',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('consent_id', sa.String(length=100), nullable=False),
    sa.Column('ip_address', sa.String(length=50), nullable=False),
    sa.Column('user_agent', sa.String(length=200), nullable=False),
    sa.Column('consent_given', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('consent_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_consent')
    # ### end Alembic commands ###
