"""Added intention guess

Revision ID: 73bec2d11114
Revises: 3b4299044394
Create Date: 2025-06-13 11:42:00.840149

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '73bec2d11114'
down_revision = '3b4299044394'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('guess_intention', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('guess_intention')

    # ### end Alembic commands ###
