"""Add investment_approach field to Response

Revision ID: 748c7d3c9832
Revises: 1a3467967745
Create Date: 2025-04-29 11:00:02.032339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '748c7d3c9832'
down_revision = '1a3467967745'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('investment_approach', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('investment_approach')

    # ### end Alembic commands ###
