"""Add feedback field

Revision ID: 85129592536c
Revises: 18ffd5d51b9d
Create Date: 2025-05-07 13:21:44.257374

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '85129592536c'
down_revision = '18ffd5d51b9d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('survey_feedback', sa.Text(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('survey_feedback')

    # ### end Alembic commands ###
