"""Add Likert reflection field to Response

Revision ID: 8a69806cf571
Revises: 748c7d3c9832
Create Date: 2025-04-29 19:10:38.145182

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a69806cf571'
down_revision = '748c7d3c9832'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.add_column(sa.Column('likert_reflection', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('response', schema=None) as batch_op:
        batch_op.drop_column('likert_reflection')

    # ### end Alembic commands ###
